import type { Metadata } from "next";
import { lexend, inter } from "./app/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lexend.variable} ${inter.variable} scroll-smooth`}
    >
      <body className="font-inter">{children}</body>
    </html>
  );
}
